services:
  frontend:
    image: caddy:latest
    container_name: frontend
    restart: always
    volumes:
      - /deploy/snoorefi/frontend:/srv/snoorefi/frontend  # Mount direktori frontend ke /srv di dalam container
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
